### ISSUE TITLE
Apache 2.4.x compatibility

### ISSUE THREAD

**Issue by drzraf** [mozilla/mod_browserid#17]
$ /usr/sbin/httpd -X -k graceful
Cannot load modules/mod_auth_browserid.so into server: /etc/httpd/modules/mod_auth_browserid.so: undefined symbol: ap_requires

**Comment by clarkevans** [comment]
Apache 2.4 is now part of Ubuntu Saucy and REHL 7 beta.   This bug prevents mod_browserid from working on newer, stock operating system installations.  Anyway we could bump the priority of the issue?

**Comment by fmarier** [comment]
A new Apache 2.4-compatible module is available here: https://github.com/mozilla/mod_authnz_persona
